name: MineZ
main: net.minezdevteam.MineZ.Main
version: 1.0
authors: [Yarno033, InstanceLabs, FerryBig, DancingWalrus]
commands:
   minez:
      description: MineZ Main user command
      permission: <plugin name>.user
      permission-message: You don't have permission.
   mineza:
      description: MineZ Main admin command
      permission: <plugin name>.admin
      permission-message: You don't have permission.
   mza:
      description: MineZ Main admin command
      permission: <plugin name>.admin
      permission-message: You don't have permission.
   mz:
      description: MineZ Main user command
      permission: <plugin name>.admin
      permission-message: You don't have permission.